name: Windows 自动编译 DLL（MSBuild）

on:
  release:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 OpenCV 4.8.0
      run: choco install opencv --version=4.8.0 -y
      shell: powershell

    - name: 安装 NuGet
      uses: nuget/setup-nuget@v2

    - name: 恢复 onnxruntime-directml 1.22.1 NuGet 包
      run: |
        nuget install Microsoft.ML.OnnxRuntime.DirectML -Version 1.22.1 -OutputDirectory $env:GITHUB_WORKSPACE/nuget_pkgs
      shell: powershell

    - name: 设置 MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: 还原 NuGet 包
      run: nuget restore OnnxDet.sln
      shell: cmd

    - name: 编译项目
      run: msbuild OnnxDet.sln /p:Configuration=Release /m
      shell: cmd

    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: dll-artifacts
        path: |
          **/Release/*.dll
          **/x64/Release/*.dll
