name: Windows 自动编译 DLL（MSBuild）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 OpenCV 4.8.0
      run: choco install opencv --version=4.8.0 -y
      shell: powershell

    - name: 安装 NuGet
      uses: nuget/setup-nuget@v2

    - name: 恢复 onnxruntime-directml 1.22.1 NuGet 包
      run: |
        nuget install Microsoft.ML.OnnxRuntime.DirectML -Version 1.22.1 -OutputDirectory $env:GITHUB_WORKSPACE/nuget_pkgs
      shell: powershell

    - name: 设置 MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: 还原 NuGet 包
      run: nuget restore OnnxDet.sln
      shell: cmd

    - name: 编译项目
      run: msbuild OnnxDet.sln /p:Configuration=Release /m
      shell: cmd

    - name: 查找 DLL 路径
      id: finddll
      run: |
        for /r %%f in (*.dll) do (
          echo ::set-output name=dllpath::%%f
          exit /b 0
        )
      shell: cmd
    
    - name: 创建 Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.COMPLIE }}

    - name: 上传 DLL 到 Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          Release/DirectML.dll
          Release/OnnxDet.dll
          Release/onnxruntime.dll
          Release/onnxruntime_providers_shared.dll
          x64/Release/DirectML.dll
          x64/Release/OnnxDet.dll
          x64/Release/onnxruntime.dll
          x64/Release/onnxruntime_providers_shared.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
