name: Windows 自动编译 DLL

on:
  release:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 OpenCV 4.8.0
      run: choco install opencv --version=4.8.0 -y
      shell: powershell

    - name: 安装 NuGet
      uses: nuget/setup-nuget@v2

    - name: 恢复 onnxruntime-directml 1.22.1 NuGet 包
      run: |
        nuget install Microsoft.ML.OnnxRuntime.DirectML -Version 1.22.1 -OutputDirectory $env:GITHUB_WORKSPACE/nuget_pkgs
      shell: powershell

    - name: 配置 CMake
      run: |
        cmake -S . -B build `
          -DOpenCV_DIR="C:/tools/opencv/build" `
          -DONNXRUNTIME_DIR="${{ github.workspace }}/nuget_pkgs/Microsoft.ML.OnnxRuntime.DirectML.1.22.1/runtimes/win-x64/native"
      shell: powershell

    - name: 编译 DLL
      run: cmake --build build --config Release
      shell: powershell

    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: dll-artifacts
        path: build/Release/*.dll
